"""Stable codes and initial published definitions for Enterprise Structure."""

WORKSPACE_TYPE_SEED = {
    "enterprise": {
        "name": "Enterprise",
        "description": "Nodo raíz que representa la empresa del tenant.",
        "allowed_children": [
            "business-unit",
            "portfolio",
            "program",
            "region",
            "site",
            "property",
            "facility",
            "warehouse",
        ],
        "can_be_root": True,
        "required_categories": [],
        "required_fields": ["code", "name"],
    },
    "business-unit": {
        "name": "Business Unit",
        "description": "Unidad de negocio, dirección, región o división empresarial.",
        "allowed_children": ["business-unit", "portfolio", "program", "property", "facility"],
        "can_be_root": False,
        "required_categories": ["responsible-area"],
        "required_fields": ["code", "name"],
    },
    "portfolio": {
        "name": "Portfolio",
        "description": "Agrupación estratégica de iniciativas, programas y proyectos.",
        "allowed_children": ["program", "project"],
        "can_be_root": False,
        "required_categories": ["strategic-objective"],
        "required_fields": ["code", "name"],
    },
    "program": {
        "name": "Program",
        "description": "Grupo coordinado de proyectos relacionados.",
        "allowed_children": ["project"],
        "can_be_root": False,
        "required_categories": ["strategic-objective"],
        "required_fields": ["code", "name"],
    },
    "project": {
        "name": "Project",
        "description": "Proyecto individual operado por los módulos de USER MODE.",
        "allowed_children": [],
        "can_be_root": False,
        "required_categories": ["strategic-objective"],
        "required_fields": ["code", "name"],
        "repeatable": True,
        "user_mode_enabled": True,
        "admin_configurable": True,
        "hierarchical_record_code": True,
        "business_numbering": True,
        "template_supported": True,
        "creation_process_supported": True,
        "allowed_parent_types": ["portfolio", "program"],
        "project_attributes": [
            {"code": "name", "label": "Nombre", "type": "text", "required": True},
            {"code": "project_number", "label": "Numero de proyecto", "type": "text", "read_only": True},
            {"code": "description", "label": "Descripcion", "type": "long_text"},
            {"code": "parent_id", "label": "Workspace padre", "type": "workspace", "required": True},
            {"code": "project_manager_id", "label": "Project Manager", "type": "user", "required": True},
            {"code": "planned_start", "label": "Inicio planificado", "type": "date"},
            {"code": "planned_finish", "label": "Fin planificado", "type": "date"},
            {"code": "currency", "label": "Moneda", "type": "currency", "required": True},
            {"code": "estimated_budget", "label": "Presupuesto estimado", "type": "decimal"},
            {"code": "project_phase", "label": "Fase", "type": "classification"},
            {"code": "country", "label": "Pais", "type": "country"},
            {"code": "region", "label": "Region", "type": "classification"},
            {"code": "priority", "label": "Prioridad", "type": "classification"},
            {
                "code": "strategic_objective",
                "label": "Objetivo estrategico",
                "type": "classification",
                "required": True,
            },
            {"code": "status", "label": "Estado", "type": "status", "required": True},
        ],
    },
    "property": {
        "name": "Property",
        "description": "Real Estate: predio, inmueble, lote o unidad inmobiliaria con identidad y gobierno propios.",
        "allowed_children": ["facility", "warehouse"],
        "can_be_root": False,
        "required_categories": ["property-type"],
        "required_fields": ["code", "name"],
        "domain_description": "Real Estate",
        "repeatable": True,
        "hierarchical_record_code": True,
        "business_numbering": True,
        "admin_configurable": True,
        "user_mode_enabled": True,
        "template_supported": True,
        "creation_process_supported": True,
        "active": True,
        "workspace_attributes": [
            "Property Name",
            "Property Number",
            "Property Type",
            "Description",
            "Ownership / Tenure",
            "Legal Status",
            "Country",
            "State / Department",
            "Municipality / City",
            "Address",
            "Postal Code",
            "Latitude",
            "Longitude",
            "Land Area",
            "Built Area",
            "Acquisition Date",
            "Book Value",
            "Market Value",
            "Responsible Area",
            "Property Manager",
            "Operational Status",
        ],
        "planned_modules": [
            "Overview",
            "Real Estate Information",
            "Documents",
            "Lease Management",
            "Property Costs",
            "Related Projects",
            "Facilities",
        ],
    },
    "facility": {
        "name": "Facility",
        "description": "Instalacion fisica u operacional administrada, independiente de Property.",
        "allowed_children": ["warehouse"],
        "can_be_root": False,
        "required_categories": ["facility-type"],
        "required_fields": ["code", "name"],
        "repeatable": True,
        "hierarchical_record_code": True,
        "business_numbering": True,
        "admin_configurable": True,
        "user_mode_enabled": True,
        "template_supported": True,
        "creation_process_supported": True,
        "active": True,
        "workspace_attributes": [
            "Facility Name",
            "Facility Number",
            "Facility Type",
            "Description",
            "Parent Workspace",
            "Responsible",
            "Operational Status",
            "Commissioning Date",
            "Gross Area",
            "Usable Area",
            "Capacity",
            "Criticality",
            "Country",
            "State / Department",
            "Municipality / City",
            "Address",
            "Postal Code",
            "Latitude",
            "Longitude",
        ],
        "planned_modules": [
            "Overview",
            "Asset Manager",
            "Maintenance",
            "Condition Assessment",
            "Space",
            "Utilities",
            "Documents",
            "Costs",
        ],
    },
    "region": {
        "name": "Region",
        "description": "Agrupacion geografica u operacional para gobierno, permisos, reporting y consolidacion.",
        "allowed_children": ["region", "district", "site", "property", "facility", "warehouse"],
        "can_be_root": False,
        "required_categories": ["responsible-area"],
        "required_fields": ["code", "name"],
        "repeatable": True,
        "hierarchical_record_code": True,
        "admin_configurable": True,
        "user_mode_enabled": True,
        "template_supported": True,
        "active": True,
        "workspace_attributes": [
            "Region Name",
            "Region Code",
            "Description",
            "Country / Countries",
            "Responsible Area",
            "Responsible",
            "Status",
        ],
    },
    "district": {
        "name": "District",
        "description": "Subdivision geografica u operacional opcional dentro de una Region.",
        "allowed_children": ["site", "property", "facility", "warehouse"],
        "can_be_root": False,
        "required_categories": [],
        "required_fields": ["code", "name"],
        "repeatable": True,
        "hierarchical_record_code": True,
        "admin_configurable": True,
        "user_mode_enabled": True,
        "template_supported": True,
        "active": True,
        "optional_level": True,
        "workspace_attributes": [
            "District Name",
            "District Code",
            "Description",
            "Region",
            "Responsible",
            "Status",
        ],
    },
    "site": {
        "name": "Site",
        "description": "Emplazamiento fisico, campus, complejo o sitio; nivel geografico opcional.",
        "allowed_children": ["property", "facility", "warehouse"],
        "can_be_root": False,
        "required_categories": [],
        "required_fields": ["code", "name"],
        "repeatable": True,
        "hierarchical_record_code": True,
        "admin_configurable": True,
        "user_mode_enabled": True,
        "template_supported": True,
        "active": True,
        "optional_level": True,
        "workspace_attributes": [
            "Site Name",
            "Site Code",
            "Description",
            "Country",
            "State / Department",
            "Municipality / City",
            "Address",
            "Postal Code",
            "Latitude",
            "Longitude",
            "Responsible",
            "Status",
        ],
    },
    "warehouse": {
        "name": "Warehouse",
        "description": "Workspace independiente y especializado para futura gestion de almacen e inventario.",
        "allowed_children": [],
        "can_be_root": False,
        "required_categories": ["warehouse-type"],
        "required_fields": ["code", "name"],
        "repeatable": True,
        "hierarchical_record_code": True,
        "business_numbering": True,
        "admin_configurable": True,
        "user_mode_enabled": True,
        "template_supported": True,
        "creation_process_supported": True,
        "active": True,
        "workspace_attributes": [
            "Warehouse Name",
            "Warehouse Number",
            "Warehouse Type",
            "Description",
            "Parent Workspace",
            "Warehouse Manager",
            "Operational Status",
            "Country",
            "State / Department",
            "Municipality / City",
            "Address",
            "Postal Code",
            "Storage Capacity",
            "Unit of Capacity",
            "Criticality",
        ],
        "planned_modules": [
            "Overview",
            "Inventory",
            "Receipts",
            "Issues",
            "Transfers",
            "Stock Locations",
            "Documents",
            "Reports",
        ],
    },
    "linear-asset": {
        "name": "Linear Asset",
        "description": "Tipo reservado para carreteras, ferrocarriles, tuberias, lineas y corredores futuros.",
        "allowed_children": [],
        "can_be_root": False,
        "required_categories": [],
        "required_fields": ["code", "name"],
        "repeatable": True,
        "hierarchical_record_code": True,
        "admin_configurable": True,
        "user_mode_enabled": False,
        "template_supported": False,
        "creation_process_supported": False,
        "active": False,
        "reserved": True,
    },
}

# Gate 06A adds operational physical Workspace Types without making them a
# prerequisite for historical CORE import/apply/publish flows. These contracts
# deliberately remain the pre-06A governance baseline.
CORE_GOVERNANCE_WORKSPACE_TYPES = {
    "enterprise",
    "business-unit",
    "portfolio",
    "program",
    "project",
    "property",
    "facility",
}
CORE_GOVERNANCE_CATEGORIES = {
    "strategic-objective",
    "responsible-area",
    "project-type",
    "property-type",
    "facility-type",
}

CATEGORY_SEED = {
    "strategic-objective": {
        "name": "Strategic Objectives",
        "description": "Objetivos estratégicos utilizados para clasificar portafolios, programas y proyectos.",
        "applicable_types": ["portfolio", "program", "project"],
        "items": [
            {"code": "growth", "label": "Growth"},
            {"code": "operational-excellence", "label": "Operational Excellence"},
            {"code": "sustainability", "label": "Sustainability"},
        ],
    },
    "responsible-area": {
        "name": "Responsible Areas",
        "description": "Áreas y centros responsables de la estructura empresarial.",
        "applicable_types": [
            "business-unit",
            "portfolio",
            "program",
            "project",
            "region",
            "district",
            "site",
            "property",
            "facility",
            "warehouse",
        ],
        "items": [
            {"code": "corporate", "label": "Corporate"},
            {"code": "capital-projects", "label": "Capital Projects"},
            {"code": "operations", "label": "Operations"},
        ],
    },
    "project-type": {
        "name": "Portfolio, Program and Project Categories",
        "description": "Clasificación inicial para la cartera de iniciativas.",
        "applicable_types": ["portfolio", "program", "project"],
        "items": [
            {"code": "capital", "label": "Capital"},
            {"code": "operational", "label": "Operational"},
            {"code": "technology", "label": "Technology"},
        ],
    },
    "property-type": {
        "name": "Property Types",
        "description": "Tipos de predio o inmueble administrado.",
        "applicable_types": ["property"],
        "items": [
            {"code": "owned", "label": "Owned"},
            {"code": "leased", "label": "Leased"},
            {"code": "concession", "label": "Concession"},
        ],
    },
    "facility-type": {
        "name": "Facility Types",
        "description": "Clasificación funcional inicial de instalaciones.",
        "applicable_types": ["facility"],
        "items": [
            {"code": "building", "label": "Building"},
            {"code": "industrial-plant", "label": "Industrial Plant"},
            {"code": "processing-plant", "label": "Processing Plant"},
            {"code": "workshop", "label": "Workshop"},
            {"code": "laboratory", "label": "Laboratory"},
            {"code": "camp", "label": "Camp"},
            {"code": "data-center", "label": "Data Center"},
            {"code": "substation", "label": "Substation"},
            {"code": "water-treatment", "label": "Water Treatment Facility"},
            {"code": "utility", "label": "Utility Facility"},
            {"code": "other", "label": "Other"},
        ],
    },
    "warehouse-type": {
        "name": "Warehouse Types",
        "description": "Clasificacion funcional inicial de almacenes.",
        "applicable_types": ["warehouse"],
        "items": [
            {"code": "general", "label": "General"},
            {"code": "distribution", "label": "Distribution"},
            {"code": "materials", "label": "Materials"},
            {"code": "cold-storage", "label": "Cold Storage"},
            {"code": "other", "label": "Other"},
        ],
    },
}

RELATIONSHIP_TYPES = {"ALIGNED_TO", "AFFECTS", "LOCATED_AT", "SERVES", "RESPONSIBLE_FOR"}
WORKSPACE_STATUSES = {"draft", "active", "inactive", "archived"}

PERMISSION_SEED = (
    ("workspace.open", "workspace", "open", "Abrir un Workspace como contexto operativo activo.", "standard"),
    ("workspace.home.read", "workspace_home", "read", "Consultar Workspace Home.", "standard"),
    ("workspace.navigator.read", "workspace_navigator", "read", "Consultar Workspace Navigator.", "standard"),
    ("workspace.recent.read", "recent_workspace", "read", "Consultar Recent Workspaces propios.", "standard"),
    ("workspace.recent.write", "recent_workspace", "write", "Actualizar ruta reciente propia.", "standard"),
    ("admin.workspace_type.read", "workspace_type", "read", "Consultar tipos de workspace.", "standard"),
    ("admin.workspace_type.manage", "workspace_type", "manage", "Administrar tipos de workspace.", "high"),
    ("admin.workspace_type.publish", "workspace_type", "publish", "Publicar tipos de workspace.", "critical"),
    (
        "admin.enterprise_structure.read",
        "enterprise_structure",
        "read",
        "Consultar la estructura empresarial.",
        "standard",
    ),
    ("admin.enterprise_structure.manage", "enterprise_structure", "manage", "Administrar nodos empresariales.", "high"),
    (
        "admin.enterprise_structure.publish",
        "enterprise_structure",
        "publish",
        "Publicar la estructura empresarial.",
        "critical",
    ),
    (
        "admin.enterprise_structure.revision.create",
        "enterprise_structure_revision",
        "create",
        "Crear revisiones CORE desde el release publicado.",
        "high",
    ),
    (
        "admin.enterprise_structure.revision.edit",
        "enterprise_structure_revision",
        "edit",
        "Editar la jerarquÃ­a dentro de una revisiÃ³n DRAFT.",
        "high",
    ),
    (
        "admin.enterprise_structure.revision.validate",
        "enterprise_structure_revision",
        "validate",
        "Validar una revisiÃ³n CORE.",
        "high",
    ),
    (
        "admin.enterprise_structure.revision.compare",
        "enterprise_structure_revision",
        "compare",
        "Comparar una revisiÃ³n contra su release publicado base.",
        "standard",
    ),
    (
        "admin.enterprise_structure.revision.approve",
        "enterprise_structure_revision",
        "approve",
        "Aprobar explÃ­citamente una revisiÃ³n CORE validada.",
        "critical",
    ),
    (
        "admin.enterprise_structure.rollback",
        "enterprise_structure_revision",
        "rollback",
        "Ejecutar rollback lÃ³gico de un release CORE.",
        "critical",
    ),
    (
        "admin.enterprise_category.read",
        "enterprise_category",
        "read",
        "Consultar categorías empresariales.",
        "standard",
    ),
    (
        "admin.enterprise_category.manage",
        "enterprise_category",
        "manage",
        "Administrar categorías empresariales.",
        "high",
    ),
    (
        "admin.enterprise_category.publish",
        "enterprise_category",
        "publish",
        "Publicar categorías empresariales.",
        "critical",
    ),
    ("admin.composition_rule.read", "composition_rule", "read", "Consultar reglas de composición.", "standard"),
    ("admin.composition_rule.manage", "composition_rule", "manage", "Administrar reglas de composición.", "high"),
    ("admin.composition_rule.publish", "composition_rule", "publish", "Publicar reglas de composición.", "critical"),
    (
        "admin.enterprise_structure.project_type.manage",
        "project_workspace_type",
        "manage",
        "Administrar la configuracion del Workspace Type PROJECT.",
        "high",
    ),
    (
        "admin.enterprise_structure.project_template.manage",
        "project_template",
        "manage",
        "Administrar plantillas de Project Workspace.",
        "high",
    ),
    (
        "admin.enterprise_structure.project_numbering.manage",
        "project_numbering",
        "manage",
        "Administrar la numeracion de Project Workspace.",
        "high",
    ),
    (
        "admin.enterprise_structure.creation_policy.manage",
        "project_creation_policy",
        "manage",
        "Administrar la politica del Project Creation Process.",
        "high",
    ),
    (
        "project_creation.request.create",
        "project_creation_request",
        "create",
        "Crear solicitudes de Project Workspace.",
        "standard",
    ),
    (
        "project_creation.request.edit",
        "project_creation_request",
        "edit",
        "Editar solicitudes propias elegibles.",
        "standard",
    ),
    (
        "project_creation.request.submit",
        "project_creation_request",
        "submit",
        "Enviar solicitudes de Project Workspace a revision.",
        "high",
    ),
    (
        "project_creation.request.read",
        "project_creation_request",
        "read",
        "Consultar solicitudes autorizadas.",
        "standard",
    ),
    (
        "project_creation.review",
        "project_creation_request",
        "review",
        "Revisar, devolver o rechazar solicitudes.",
        "high",
    ),
    (
        "project_creation.approve",
        "project_creation_request",
        "approve",
        "Aprobar solicitudes con Four-Eyes.",
        "critical",
    ),
    (
        "project_creation.materialize",
        "project_creation_request",
        "materialize",
        "Materializar Project Workspaces aprobados.",
        "critical",
    ),
    (
        "project_workspace.initialization.read",
        "project_workspace_initialization",
        "read",
        "Consultar el estado, preview y checklist de inicializacion de Project Workspaces.",
        "standard",
    ),
    (
        "project_workspace.initialization.execute",
        "project_workspace_initialization",
        "execute",
        "Inicializar y validar Project Workspaces materializados.",
        "high",
    ),
    (
        "project_workspace.activation.execute",
        "project_workspace_activation",
        "execute",
        "Activar Project Workspaces listos con separacion de funciones.",
        "critical",
    ),
    (
        "admin.enterprise_structure.geography.manage",
        "physical_workspace_configuration",
        "manage_geography",
        "Administrar Region, District, Site y sus reglas fisicas.",
        "high",
    ),
    (
        "admin.enterprise_structure.property.manage",
        "physical_workspace_configuration",
        "manage_property",
        "Administrar la configuracion PROPERTY (Real Estate).",
        "high",
    ),
    (
        "admin.enterprise_structure.facility.manage",
        "physical_workspace_configuration",
        "manage_facility",
        "Administrar la configuracion FACILITY.",
        "high",
    ),
    (
        "admin.enterprise_structure.warehouse.manage",
        "physical_workspace_configuration",
        "manage_warehouse",
        "Administrar la configuracion WAREHOUSE.",
        "high",
    ),
    (
        "admin.enterprise_structure.physical_templates.manage",
        "physical_template",
        "manage",
        "Administrar plantillas fisicas sin publicacion automatica.",
        "high",
    ),
    (
        "admin.enterprise_structure.physical_numbering.manage",
        "physical_numbering",
        "manage",
        "Administrar numeracion tenant-scoped de Workspaces fisicos.",
        "high",
    ),
    (
        "admin.enterprise_structure.physical_policy.manage",
        "physical_creation_policy",
        "manage",
        "Administrar politicas DRAFT de creacion fisica.",
        "high",
    ),
    (
        "physical_workspace_creation.request.create",
        "physical_workspace_creation_request",
        "create",
        "Crear solicitudes parametrizadas de Property, Facility o Warehouse.",
        "standard",
    ),
    (
        "physical_workspace_creation.request.edit",
        "physical_workspace_creation_request",
        "edit",
        "Editar solicitudes fisicas propias elegibles.",
        "standard",
    ),
    (
        "physical_workspace_creation.request.submit",
        "physical_workspace_creation_request",
        "submit",
        "Enviar solicitudes fisicas a revision.",
        "high",
    ),
    (
        "physical_workspace_creation.request.read",
        "physical_workspace_creation_request",
        "read",
        "Consultar solicitudes fisicas autorizadas.",
        "standard",
    ),
    (
        "physical_workspace_creation.review",
        "physical_workspace_creation_request",
        "review",
        "Revisar, devolver o rechazar solicitudes fisicas.",
        "high",
    ),
    (
        "physical_workspace_creation.approve",
        "physical_workspace_creation_request",
        "approve",
        "Aprobar solicitudes fisicas con Four-Eyes.",
        "critical",
    ),
    (
        "physical_workspace_creation.materialize",
        "physical_workspace_creation_request",
        "materialize",
        "Materializar Workspaces fisicos aprobados.",
        "critical",
    ),
    (
        "physical_workspace.initialization.read",
        "physical_workspace_initialization",
        "read",
        "Consultar preview, checklist y estado de inicializacion de Workspaces fisicos.",
        "standard",
    ),
    (
        "physical_workspace.initialization.execute",
        "physical_workspace_initialization",
        "execute",
        "Inicializar, reintentar y validar Workspaces fisicos materializados.",
        "high",
    ),
    (
        "physical_workspace.activation.execute",
        "physical_workspace_activation",
        "execute",
        "Activar Workspaces fisicos listos bajo separacion de funciones.",
        "critical",
    ),
    ("enterprise_structure.read", "enterprise_structure", "read", "Consultar Enterprise Explorer.", "standard"),
    (
        "enterprise_structure.read_history",
        "enterprise_structure",
        "read_history",
        "Consultar historial empresarial.",
        "high",
    ),
    ("enterprise_structure.export", "enterprise_structure", "export", "Exportar la estructura autorizada.", "high"),
    ("idea.read", "idea", "read", "Consultar ideas autorizadas.", "standard"),
    ("idea.create", "idea", "create", "Crear ideas en un Workspace empresarial autorizado.", "standard"),
    ("idea.edit", "idea", "edit", "Editar ideas elegibles.", "standard"),
    ("idea.submit", "idea", "submit", "Enviar ideas al proceso de intake.", "high"),
    ("idea.screen", "idea", "screen", "Ejecutar screening y devolver ideas.", "high"),
    ("idea.route", "idea", "route", "Definir el enrutamiento controlado de ideas.", "high"),
    ("idea.assign_owner", "idea", "assign_owner", "Asignar un responsable autorizado a una idea.", "high"),
    ("idea.evaluate", "idea", "evaluate", "Evaluar ideas con una matriz publicada.", "high"),
    ("idea.decide", "idea", "decide", "Aceptar o rechazar ideas evaluadas.", "critical"),
    ("idea.cancel", "idea", "cancel", "Cancelar ideas elegibles.", "high"),
    ("idea.admin.configure", "idea_configuration", "configure", "Configurar Idea & Demand Manager.", "high"),
    ("idea.admin.publish", "idea_configuration", "publish", "Publicar configuracion de ideas.", "critical"),
    ("project_proposal.read", "project_proposal", "read", "Consultar Project Proposals autorizadas.", "standard"),
    ("project_proposal.create", "project_proposal", "create", "Crear Proposal desde una Idea aceptada.", "high"),
    ("project_proposal.edit", "project_proposal", "edit", "Editar Project Proposals elegibles.", "standard"),
    ("project_proposal.submit", "project_proposal", "submit", "Enviar una Project Proposal a revision.", "high"),
    ("project_proposal.review", "project_proposal", "review", "Revisar Project Proposals.", "high"),
    ("project_proposal.return", "project_proposal", "return", "Devolver una Proposal para correccion.", "high"),
    ("project_proposal.evaluate", "project_proposal", "evaluate", "Evaluar Project Proposals.", "high"),
    (
        "project_proposal.mark_gate_ready",
        "project_proposal",
        "mark_gate_ready",
        "Declarar una Proposal lista para el Strategic Gate.",
        "critical",
    ),
    ("project_proposal.cancel", "project_proposal", "cancel", "Cancelar Project Proposals elegibles.", "high"),
    (
        "project_proposal.admin.configure",
        "project_proposal_configuration",
        "configure",
        "Configurar el ciclo Project Proposal.",
        "high",
    ),
    (
        "project_proposal.admin.publish",
        "project_proposal_configuration",
        "publish",
        "Publicar configuracion de Project Proposal.",
        "critical",
    ),
)
