DEFAULT_PROCESS_TEMPLATES = [
    {
        "code": "PJ-CREATE",
        "name": "Project Creation",
        "category": "Administration",
        "description": "Creates the project control record, assigns the core team and opens the schedule intake gate.",
        "form_schema": ["Project code", "Project name", "Phase", "Dates", "Currency"],
        "status": "Active",
        "version_no": 1,
        "steps": [
            {
                "name": "Creation",
                "detail": "Project and governance metadata are captured.",
                "owner_role": "Control Manager",
                "status": "Active",
                "tone": "active",
            },
            {
                "name": "Team Assignment",
                "detail": "Project users, role profiles and permissions are assigned.",
                "owner_role": "Control Manager",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Schedule Gate",
                "detail": "Source schedule upload becomes the master workflow trigger.",
                "owner_role": "Planner",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Activation",
                "detail": "The project is ready for integrated project controls execution.",
                "owner_role": "Control Manager",
                "status": "Queued",
                "tone": "queued",
            },
        ],
        "transitions": [
            {
                "action": "assign_team",
                "label": "Assign Team",
                "from_step": "Creation",
                "to_step": "Team Assignment",
                "process_status": "in_review",
                "ball_in_court": "Control Manager",
            },
            {
                "action": "open_schedule_gate",
                "label": "Open Schedule Gate",
                "from_step": "Team Assignment",
                "to_step": "Schedule Gate",
                "process_status": "in_review",
                "ball_in_court": "Planner",
            },
        ],
    },
    {
        "code": "SCH-INTAKE",
        "name": "Schedule Intake",
        "category": "Planning / Baseline",
        "description": "Turns a Primavera P6 or source schedule XML/XER into the control baseline workflow.",
        "form_schema": ["Schedule file", "Data date", "Baseline", "Logic quality", "Activity mapping"],
        "status": "Active",
        "version_no": 1,
        "steps": [
            {
                "name": "Creation",
                "detail": "Source schedule file received.",
                "owner_role": "Planner",
                "status": "Complete",
                "tone": "complete",
            },
            {
                "name": "Data Quality",
                "detail": "DCMA/AACE schedule quality, logic and baseline checks passed.",
                "owner_role": "Controls Engineer",
                "status": "Complete",
                "tone": "complete",
            },
            {
                "name": "Impact Review",
                "detail": "Schedule, cost, progress and contractual exposure analysis.",
                "owner_role": "Project Controls",
                "status": "Active",
                "tone": "active",
            },
            {
                "name": "Approval",
                "detail": "Control Manager decision on baseline acceptance.",
                "owner_role": "Control Manager",
                "status": "Pending",
                "tone": "pending",
            },
            {
                "name": "Action",
                "detail": "Forecast, lookahead, communication and audit updates.",
                "owner_role": "Execution Lead",
                "status": "Queued",
                "tone": "queued",
            },
        ],
        "transitions": [
            {
                "action": "route_to_approval",
                "label": "Route to Approval",
                "from_step": "Impact Review",
                "to_step": "Approval",
                "process_status": "in_review",
                "ball_in_court": "Control Manager",
                "permission_key": "",
            },
            {
                "action": "approve_baseline",
                "label": "Approve Baseline",
                "from_step": "Approval",
                "to_step": "Action",
                "process_status": "approved",
                "ball_in_court": "Execution Lead",
                "requires_approval": True,
                "permission_key": "can_approve_workflow",
            },
            {
                "action": "reject_baseline",
                "label": "Reject",
                "from_step": "Approval",
                "to_step": "Data Quality",
                "process_status": "rejected",
                "ball_in_court": "Planning Lead",
                "from_status": "Rejected",
                "from_tone": "critical",
                "to_status": "Active",
                "to_tone": "active",
                "requires_approval": True,
                "permission_key": "can_approve_workflow",
            },
            {
                "action": "close_action",
                "label": "Close Action Loop",
                "from_step": "Action",
                "to_step": "Closed",
                "process_status": "closed",
                "ball_in_court": "Control Core",
                "requires_approval": True,
                "permission_key": "can_approve_workflow",
            },
        ],
    },
    {
        "code": "CR-CONTROL",
        "name": "Change Request",
        "category": "Change Management",
        "description": "Routes deviations through impact analysis, contractual review, approval and implementation tracking.",
        "form_schema": ["Deviation", "Cost impact", "Schedule impact", "Cause", "Supporting documents"],
        "status": "Active",
        "version_no": 1,
        "steps": [
            {
                "name": "Initiation",
                "detail": "Deviation and potential change are captured.",
                "owner_role": "Originator",
                "status": "Active",
                "tone": "active",
            },
            {
                "name": "Impact Review",
                "detail": "Cost, schedule and productivity impacts are evaluated.",
                "owner_role": "Project Controls",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Contract Review",
                "detail": "Contract basis, notices and communications are checked.",
                "owner_role": "Contract Manager",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Approval",
                "detail": "Control governance approves or rejects the change.",
                "owner_role": "Control Manager",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Implementation",
                "detail": "Approved disposition updates forecast, budget and action log.",
                "owner_role": "Execution Lead",
                "status": "Queued",
                "tone": "queued",
            },
        ],
        "transitions": [
            {
                "action": "submit_change",
                "label": "Submit Change",
                "from_step": "Initiation",
                "to_step": "Impact Review",
                "process_status": "in_review",
                "ball_in_court": "Project Controls",
            },
            {
                "action": "route_contract_review",
                "label": "Route Contract Review",
                "from_step": "Impact Review",
                "to_step": "Contract Review",
                "process_status": "in_review",
                "ball_in_court": "Contract Manager",
            },
            {
                "action": "approve_change",
                "label": "Approve Change",
                "from_step": "Approval",
                "to_step": "Implementation",
                "process_status": "approved",
                "ball_in_court": "Execution Lead",
                "requires_approval": True,
                "permission_key": "can_approve_workflow",
            },
        ],
    },
    {
        "code": "CON-COMM",
        "name": "Contract Communication",
        "category": "Contract Administration",
        "description": "Controls contractual communications, notices and their linkage to changes, claims and evidence.",
        "form_schema": ["Contract", "Communication type", "Subject", "Reference", "Date"],
        "status": "Active",
        "version_no": 1,
        "steps": [
            {
                "name": "Draft",
                "detail": "Communication content and contract reference are drafted.",
                "owner_role": "Contract Manager",
                "status": "Active",
                "tone": "active",
            },
            {
                "name": "Contract Review",
                "detail": "Notice requirements and timing are verified.",
                "owner_role": "Contract Manager",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Issue",
                "detail": "Communication is formally issued.",
                "owner_role": "Control Manager",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Link Evidence",
                "detail": "Issued record is linked to events, changes, claims or documents.",
                "owner_role": "Document Control",
                "status": "Queued",
                "tone": "queued",
            },
        ],
        "transitions": [
            {
                "action": "route_contract_review",
                "label": "Route Review",
                "from_step": "Draft",
                "to_step": "Contract Review",
                "process_status": "in_review",
                "ball_in_court": "Contract Manager",
            },
            {
                "action": "issue_communication",
                "label": "Issue",
                "from_step": "Contract Review",
                "to_step": "Issue",
                "process_status": "approved",
                "ball_in_court": "Control Manager",
                "permission_key": "can_manage_contract",
            },
        ],
    },
    {
        "code": "RFQ-BID",
        "name": "RFQ / Bid Evaluation",
        "category": "Preconstruction / Procurement",
        "description": "Controls RFQ package issue, bid receipt, commercial/technical leveling and award recommendation.",
        "form_schema": [
            "RFQ package",
            "Work description",
            "Budget",
            "Bidder",
            "Bid amount",
            "Technical score",
            "Commercial score",
            "Schedule score",
            "Risk score",
        ],
        "status": "Active",
        "version_no": 1,
        "steps": [
            {
                "name": "Package Setup",
                "detail": "Work description, budget, control account and due date are defined.",
                "owner_role": "Contract Manager",
                "status": "Active",
                "tone": "active",
            },
            {
                "name": "Issue / Invite",
                "detail": "RFQ is issued and bidders are invited with document requirements.",
                "owner_role": "Contract Manager",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Bid Receipt",
                "detail": "Bid amount and bidder submission metadata are captured.",
                "owner_role": "Contract Manager",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Bid Leveling",
                "detail": "Technical, commercial, schedule and risk scores are reviewed.",
                "owner_role": "Project Controls",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Award Recommendation",
                "detail": "Recommended bidder is selected for contract or purchase order action.",
                "owner_role": "Control Manager",
                "status": "Queued",
                "tone": "queued",
            },
        ],
        "transitions": [
            {
                "action": "issue_rfq",
                "label": "Issue RFQ",
                "from_step": "Package Setup",
                "to_step": "Issue / Invite",
                "process_status": "in_review",
                "ball_in_court": "Contract Manager",
                "permission_key": "can_manage_contract",
            },
            {
                "action": "receive_bid",
                "label": "Receive Bid",
                "from_step": "Issue / Invite",
                "to_step": "Bid Receipt",
                "process_status": "in_review",
                "ball_in_court": "Contract Manager",
                "permission_key": "can_manage_contract",
            },
            {
                "action": "level_bid",
                "label": "Level Bid",
                "from_step": "Bid Receipt",
                "to_step": "Bid Leveling",
                "process_status": "in_review",
                "ball_in_court": "Project Controls",
            },
            {
                "action": "recommend_award",
                "label": "Recommend Award",
                "from_step": "Bid Leveling",
                "to_step": "Award Recommendation",
                "process_status": "approved",
                "ball_in_court": "Control Manager",
                "requires_approval": True,
                "permission_key": "can_approve_workflow",
            },
        ],
    },
    {
        "code": "DOC-LINK",
        "name": "Document Link",
        "category": "Document Control",
        "description": "Links documents to the control object that needs traceability across schedule, cost, change or claim records.",
        "form_schema": ["Linked entity", "Document type", "Title", "Repository URI"],
        "status": "Active",
        "version_no": 1,
        "steps": [
            {
                "name": "Capture",
                "detail": "Document metadata and repository location are captured.",
                "owner_role": "Document Control",
                "status": "Active",
                "tone": "active",
            },
            {
                "name": "Classify",
                "detail": "Document type and contractual relevance are classified.",
                "owner_role": "Project Controls",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Link",
                "detail": "Document is linked to the governing control record.",
                "owner_role": "Document Control",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Audit",
                "detail": "Traceability is visible in the audit trail.",
                "owner_role": "Control Manager",
                "status": "Queued",
                "tone": "queued",
            },
        ],
        "transitions": [
            {
                "action": "classify_document",
                "label": "Classify",
                "from_step": "Capture",
                "to_step": "Classify",
                "process_status": "in_review",
                "ball_in_court": "Project Controls",
            },
            {
                "action": "link_document",
                "label": "Link",
                "from_step": "Classify",
                "to_step": "Link",
                "process_status": "approved",
                "ball_in_court": "Document Control",
            },
        ],
    },
    {
        "code": "AWP-READY",
        "name": "AWP Readiness",
        "category": "Advanced Work Packaging",
        "description": "Controls path of construction, package work content, constraints and release readiness for workface execution.",
        "form_schema": ["Package type", "Path of construction", "Control account", "Constraints", "Release status"],
        "status": "Active",
        "version_no": 1,
        "steps": [
            {
                "name": "Path Definition",
                "detail": "Path of construction and sequence are aligned with the approved schedule.",
                "owner_role": "Planner",
                "status": "Complete",
                "tone": "complete",
            },
            {
                "name": "Package Definition",
                "detail": "CWA/CWP/EWP/PWP/IWP work content is tied to control accounts and deliverables.",
                "owner_role": "Workface Planner",
                "status": "Complete",
                "tone": "complete",
            },
            {
                "name": "Constraint Review",
                "detail": "Open constraints determine workface readiness.",
                "owner_role": "Workface Planner",
                "status": "Active",
                "tone": "active",
            },
            {
                "name": "Release",
                "detail": "Ready package can be released to field execution.",
                "owner_role": "Construction Manager",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Execute",
                "detail": "Field progress feeds Control Core and AWP status.",
                "owner_role": "Field Engineer",
                "status": "Queued",
                "tone": "queued",
            },
        ],
        "transitions": [
            {
                "action": "release_work_package",
                "label": "Release Package",
                "from_step": "Constraint Review",
                "to_step": "Release",
                "process_status": "approved",
                "ball_in_court": "Construction Manager",
            },
            {
                "action": "start_execution",
                "label": "Start Execution",
                "from_step": "Release",
                "to_step": "Execute",
                "process_status": "in_review",
                "ball_in_court": "Field Engineer",
            },
        ],
    },
    {
        "code": "CL-FORENSIC",
        "name": "Claim Event",
        "category": "Claims / Forensic",
        "description": "Builds entitlement through event definition, notice, causation, impact, quantum and evidence.",
        "form_schema": [
            "Contract basis",
            "Change/event",
            "Notice",
            "Causation",
            "Schedule impact",
            "Quantum",
            "Mitigation",
            "Evidence",
        ],
        "status": "Configured",
        "version_no": 1,
        "steps": [
            {
                "name": "Event Capture",
                "detail": "Claim event, affected control account and evidence package are captured.",
                "owner_role": "Field Lead",
                "status": "Complete",
                "tone": "complete",
            },
            {
                "name": "Notice Review",
                "detail": "Contract notice, timing and procedural compliance are checked.",
                "owner_role": "Contract Manager",
                "status": "Active",
                "tone": "active",
            },
            {
                "name": "Causation Review",
                "detail": "Cause-and-effect analysis links event, schedule, productivity and cost impact.",
                "owner_role": "Claims Analyst",
                "status": "Active",
                "tone": "active",
            },
            {
                "name": "Impact / Quantum Analysis",
                "detail": "Schedule impact, productivity loss and damages are quantified.",
                "owner_role": "Project Controls",
                "status": "Pending",
                "tone": "pending",
            },
            {
                "name": "Entitlement Position",
                "detail": "Contract position and recovery strategy are approved.",
                "owner_role": "Control Manager",
                "status": "Queued",
                "tone": "queued",
            },
        ],
        "transitions": [
            {
                "action": "route_notice_review",
                "label": "Route Notice Review",
                "from_step": "Event Capture",
                "to_step": "Notice Review",
                "process_status": "in_review",
                "ball_in_court": "Contract Manager",
            },
            {
                "action": "route_causation_review",
                "label": "Route Causation Review",
                "from_step": "Notice Review",
                "to_step": "Causation Review",
                "process_status": "in_review",
                "ball_in_court": "Claims Analyst",
            },
            {
                "action": "approve_entitlement",
                "label": "Approve Entitlement",
                "from_step": "Entitlement Position",
                "to_step": "Closed",
                "process_status": "approved",
                "ball_in_court": "Control Core",
                "requires_approval": True,
                "permission_key": "can_approve_workflow",
            },
        ],
    },
    {
        "code": "CL-CUM-IMPACT",
        "name": "Cumulative Impact Claim",
        "category": "Claims / Forensic",
        "description": "Structures cumulative impact analysis around change saturation, productivity baseline, causation and damages.",
        "form_schema": [
            "Change population",
            "Impacted period",
            "Productivity baseline",
            "Measured mile",
            "Disruption factors",
            "Causal link",
            "Damages",
        ],
        "status": "Configured",
        "version_no": 1,
        "steps": [
            {
                "name": "Change Saturation Review",
                "detail": "Population and timing of changes are defined.",
                "owner_role": "Claims Analyst",
                "status": "Active",
                "tone": "active",
            },
            {
                "name": "Productivity Analysis",
                "detail": "Measured mile or baseline productivity analysis is prepared.",
                "owner_role": "Project Controls",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Cause Segregation",
                "detail": "Discrete, cumulative and contractor-responsible causes are separated.",
                "owner_role": "Claims Analyst",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Quantum Review",
                "detail": "Productivity loss is translated into recoverable cost.",
                "owner_role": "Project Controls",
                "status": "Queued",
                "tone": "queued",
            },
            {
                "name": "Entitlement Position",
                "detail": "Cumulative impact position is reviewed for recovery strategy.",
                "owner_role": "Control Manager",
                "status": "Queued",
                "tone": "queued",
            },
        ],
        "transitions": [
            {
                "action": "start_productivity_analysis",
                "label": "Productivity Analysis",
                "from_step": "Change Saturation Review",
                "to_step": "Productivity Analysis",
                "process_status": "in_review",
                "ball_in_court": "Project Controls",
            },
            {
                "action": "route_cause_segregation",
                "label": "Cause Segregation",
                "from_step": "Productivity Analysis",
                "to_step": "Cause Segregation",
                "process_status": "in_review",
                "ball_in_court": "Claims Analyst",
            },
        ],
    },
]


def default_template_by_code(code: str) -> dict | None:
    return next((template for template in DEFAULT_PROCESS_TEMPLATES if template["code"] == code), None)
